name: build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-26.04
          - runner: ubuntu-26.04-arm
          - runner: xcode-27
          - runner: macos-26-intel
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: build-alpine-image
        if: ${{ runner.os == 'Linux' }}
        run: |
          pushd "$(mktemp -d)"
          curl -f -L https://github.com/haskell-wasm/rust-alpine-mimalloc/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
          podman build \
            --pull \
            --tag rust:alpine-mimalloc \
            .
          popd

      - name: build-alpine
        if: ${{ runner.os == 'Linux' }}
        run: |
          podman run \
            --init \
            --rm \
            --volume $PWD:/workspace \
            --workdir /workspace \
            rust:alpine-mimalloc \
            /workspace/build-alpine.sh

      - name: build-macos
        if: ${{ runner.os == 'macOS' }}
        run: |
          ./build-macos.sh

      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: node-${{ runner.os }}-${{ runner.arch }}
          path: dist/node-v*.tar.xz

      - name: test-node
        run: |
          pushd dist
          tar xJf node-v*.tar.xz --strip-components=1
          export PATH=$PWD/bin:$PATH
          npm install @bjorn3/browser_wasi_shim
          popd

  release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: publish-release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh release create ${{ github.ref_name }} node-v*.tar.xz \
            --title ${{ github.ref_name }} \
            --notes-file /dev/null \
            --latest \
            --verify-tag
