name: build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build-image
        run: |
          pushd "$(mktemp -d)"
          curl -f -L https://github.com/haskell-wasm/rust-alpine-mimalloc/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
          podman build \
            --pull \
            --tag rust:alpine-mimalloc \
            .
          popd

      - name: build-node
        run: |
          podman run \
            --init \
            --rm \
            --volume $PWD:/workspace \
            --workdir /workspace \
            rust:alpine-mimalloc \
            /workspace/build-alpine.sh

      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: node-linux-${{ matrix.arch }}
          path: dist/node-v*.tar.xz

      - name: test-node
        run: |
          pushd dist
          tar xJf node-v*.tar.xz --strip-components=1
          export PATH=$PWD/bin:$PATH
          npm install @bjorn3/browser_wasi_shim
          popd
